name: Brandon Hensinger
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6729239642154425
title: Brandon Hensinger
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff981f'
    - '#363433'
    - '#9a9cb7'
    - '#d9e0f2'
    - '#294de1'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 0.125
  rhythmicContrast: 0.396286781411618
purpose: []
