name: Brandon Hensinger
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6729239642154425
title: Brandon Hensinger
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#a8682c'
    - '#6c4424'
    - '#af9276'
    - '#d9b998'
  brandStrength: 0.2929299271199852
  lightness: 0.7691243225708604
  saturation: 0.19795723701827228
  rhythmicContrast: 0.396286781411618
purpose: []
